<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile.proto

namespace Pakutoma\Phreakscope\protobuf\profiles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>perftools.profiles.Line</code>
 */
class Line extends \Google\Protobuf\Internal\Message
{
    /**
     * The id of the corresponding profile.Function for this line.
     *
     * Generated from protobuf field <code>uint64 function_id = 1;</code>
     */
    protected $function_id = 0;
    /**
     * Line number in source code.
     *
     * Generated from protobuf field <code>int64 line = 2;</code>
     */
    protected $line = 0;
    /**
     * Column number in source code.
     *
     * Generated from protobuf field <code>int64 column = 3;</code>
     */
    protected $column = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $function_id
     *           The id of the corresponding profile.Function for this line.
     *     @type int|string $line
     *           Line number in source code.
     *     @type int|string $column
     *           Column number in source code.
     * }
     */
    public function __construct($data = NULL) {
        \Pakutoma\Phreakscope\protobuf\metadata\Profile::initOnce();
        parent::__construct($data);
    }

    /**
     * The id of the corresponding profile.Function for this line.
     *
     * Generated from protobuf field <code>uint64 function_id = 1;</code>
     * @return int|string
     */
    public function getFunctionId()
    {
        return $this->function_id;
    }

    /**
     * The id of the corresponding profile.Function for this line.
     *
     * Generated from protobuf field <code>uint64 function_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFunctionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->function_id = $var;

        return $this;
    }

    /**
     * Line number in source code.
     *
     * Generated from protobuf field <code>int64 line = 2;</code>
     * @return int|string
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * Line number in source code.
     *
     * Generated from protobuf field <code>int64 line = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLine($var)
    {
        GPBUtil::checkInt64($var);
        $this->line = $var;

        return $this;
    }

    /**
     * Column number in source code.
     *
     * Generated from protobuf field <code>int64 column = 3;</code>
     * @return int|string
     */
    public function getColumn()
    {
        return $this->column;
    }

    /**
     * Column number in source code.
     *
     * Generated from protobuf field <code>int64 column = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setColumn($var)
    {
        GPBUtil::checkInt64($var);
        $this->column = $var;

        return $this;
    }

}

