<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: profile.proto

namespace Pakutoma\Phreakscope\protobuf\profiles;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>perftools.profiles.Function</code>
 */
class PBFunction extends \Google\Protobuf\Internal\Message
{
    /**
     * Unique nonzero id for the function.
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Name of the function, in human-readable form if available.
     *
     * Generated from protobuf field <code>int64 name = 2;</code>
     */
    protected $name = 0;
    /**
     * Name of the function, as identified by the system.
     * For instance, it can be a C++ mangled name.
     *
     * Generated from protobuf field <code>int64 system_name = 3;</code>
     */
    protected $system_name = 0;
    /**
     * Source file containing the function.
     *
     * Generated from protobuf field <code>int64 filename = 4;</code>
     */
    protected $filename = 0;
    /**
     * Line number in source file.
     *
     * Generated from protobuf field <code>int64 start_line = 5;</code>
     */
    protected $start_line = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *           Unique nonzero id for the function.
     *     @type int|string $name
     *           Name of the function, in human-readable form if available.
     *     @type int|string $system_name
     *           Name of the function, as identified by the system.
     *           For instance, it can be a C++ mangled name.
     *     @type int|string $filename
     *           Source file containing the function.
     *     @type int|string $start_line
     *           Line number in source file.
     * }
     */
    public function __construct($data = NULL) {
        \Pakutoma\Phreakscope\protobuf\metadata\Profile::initOnce();
        parent::__construct($data);
    }

    /**
     * Unique nonzero id for the function.
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Unique nonzero id for the function.
     *
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Name of the function, in human-readable form if available.
     *
     * Generated from protobuf field <code>int64 name = 2;</code>
     * @return int|string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name of the function, in human-readable form if available.
     *
     * Generated from protobuf field <code>int64 name = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkInt64($var);
        $this->name = $var;

        return $this;
    }

    /**
     * Name of the function, as identified by the system.
     * For instance, it can be a C++ mangled name.
     *
     * Generated from protobuf field <code>int64 system_name = 3;</code>
     * @return int|string
     */
    public function getSystemName()
    {
        return $this->system_name;
    }

    /**
     * Name of the function, as identified by the system.
     * For instance, it can be a C++ mangled name.
     *
     * Generated from protobuf field <code>int64 system_name = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSystemName($var)
    {
        GPBUtil::checkInt64($var);
        $this->system_name = $var;

        return $this;
    }

    /**
     * Source file containing the function.
     *
     * Generated from protobuf field <code>int64 filename = 4;</code>
     * @return int|string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Source file containing the function.
     *
     * Generated from protobuf field <code>int64 filename = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFilename($var)
    {
        GPBUtil::checkInt64($var);
        $this->filename = $var;

        return $this;
    }

    /**
     * Line number in source file.
     *
     * Generated from protobuf field <code>int64 start_line = 5;</code>
     * @return int|string
     */
    public function getStartLine()
    {
        return $this->start_line;
    }

    /**
     * Line number in source file.
     *
     * Generated from protobuf field <code>int64 start_line = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartLine($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_line = $var;

        return $this;
    }

}

